### ISSUE TITLE
Infografía Calidad y Tipos de Pruebas - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Edwin14459#1]
[Infografía Calidad y Tipos de Pruebas - Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Edwin14459/files/15475137/Infografia.Calidad.y.Tipos.de.Pruebas.-.Edwin.Lopez.Santiago.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Calificacion 20
